name: CI

on: [
  push,
  pull_request,
  workflow_dispatch
]

env:
  PYTHON_VERSION: "3.11"

jobs:
# ==============================================================================

  release:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master' && github.repository == 'apple1417/oak-sdk-mods'

    needs:
      - spelling
      - pyright
      - ruff

    permissions:
      contents: write

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: ${{ env.PYTHON_VERSION }}

    - name: Prepease releases
      run: ./prepare_releases.py

    - name: Upload releases
      uses: andelf/nightly-release@main
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: nightly
        files: |
          *.sdkmod
          *.zip
        prerelease: false
        name: Automated Releases
        body: >
          This release is automatically built from the latest (passing) commits on master.

# ==============================================================================

  spelling:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Check spelling
      uses: crate-ci/typos@master

  pyright:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        path: oak-sdk-mods

    - name: Checkout pyunrealsdk
      uses: actions/checkout@v4
      with:
        repository: bl-sdk/pyunrealsdk
        path: pyunrealsdk

    - name: Checkout oak-mod-manager
      uses: actions/checkout@v4
      with:
        repository: bl-sdk/oak-mod-manager
        path: oak-mod-manager

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: ${{ env.PYTHON_VERSION }}
        cache: 'pip'

    - name: Install tomlq
      run: pip install yq

    - name: Add stub paths to pyproject.toml
      run: >
        tomlq -it '.tool.pyright.extraPaths =
        ["../pyunrealsdk/stubs",
        "../oak-mod-manager/src"]'
        oak-sdk-mods/pyproject.toml

    - name: Run pyright
      uses: jakebailey/pyright-action@v1
      with:
        working-directory: oak-sdk-mods

  ruff:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Run Ruff Linting
      uses: chartboost/ruff-action@v1

    - name: Run Ruff Formatting
      uses: chartboost/ruff-action@v1
      with:
        args: format --check
